# Generated by Django 4.1.3 on 2022-12-22 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatchStatus',
            fields=[
                ('id', models.CharField(default='5q7eBH9hHs1qelDEQq8jaVTh', max_length=24, primary_key=True, serialize=False)),
                ('status_type', models.CharField(choices=[('STA', 'Start'), ('BRE', 'Break'), ('RES', 'Resumption'), ('GOA', 'Goal'), ('END', 'End'), ('OTH', 'Other')], max_length=3)),
                ('info', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('scoreboard', models.CharField(max_length=255)),
                ('uidPlayer', models.CharField(max_length=255)),
            ],
        ),
    ]
